### ISSUE TITLE
Any plans to support creating Custom Event integrations?

### ISSUE THREAD

**Issue by kiwimato** [OpsLevel/terraform-provider-opslevel#158]
Hey guys,

We're currently working on building using Terraform and want to create Custom Event integrations. I found Custom event checks is supported, but can't find a way to create the actual Custom Event integration using either Terraform or GraphQL.

To make it clear, I'm talking about the resource that data resource `opslevel_integration` can find. Right now I'm creating it manually in the UI and noticed that even there when it gets created, there's a POST call to `https://app.opslevel.com/api/integrations/events` and not to the actual GraphQL API which makes me think that it's not supported using GraphQL either. Also I noticed that the API tokens only work for GraphQL and not for the endpoint I just mentioned.

Am I right to say that the only solution right now is to create it using the UI and fetch it using a data source? Or am I missing something?

Thank you!

**Comment by rocktavious** [comment]
Hey @kiwimato - Sorry for the long radio silence on this one but we've finally got the GraphQL API into a place where this is now possible.  We will be scheduling to add this functionality to the Terraform provider in the coming weeks.

**Comment by davidbloss** [comment]
Unable to finish the Terraform work as these integrations cannot be deleted via the API
