### ISSUE TITLE
Don't remove members assigned to teams in the UI

### ISSUE THREAD

**Issue by GilUpstream** [OpsLevel/terraform-provider-opslevel#183]
We're looking to update to the latest version for the tf provider, but we're getting plans where members are removed from our teams (folks self select their teams from prompting from OpsLevel on first login). Looks like there was a [previous attempt](https://github.com/OpsLevel/terraform-provider-opslevel/pull/162) at fixing this issue, but it had a [regression](https://github.com/OpsLevel/terraform-provider-opslevel/pull/162#issuecomment-1858205343). 

Are there any plans to address this or are there known workarounds?

**Comment by rocktavious** [comment]
Hey @GilUpstream - There is a bigger systemic problem here that we cannot fix easily.  One of the people on my team said `there's no reliable way to fix this except for upgrading to a new terraform provider.`  So we are looking into what it takes to upgrade our Terraform SDK version to the latest.  This will likely be multiple months of effort 😞

**Comment by rocktavious** [comment]
@davidbloss - I got clarification from @GilUpstream on what exactly they were running up against and I now have a better understanding of what we should do here.  Lets sync up when you are back.

**Comment by davidbloss** [comment]
@GilUpstream thank you for pointing this out!
This issue has been resolved and will be included in the next release.
