### ISSUE TITLE
Can't make filter with repository_ids exists.

### ISSUE THREAD

**Issue by cmanfre4** [OpsLevel/terraform-provider-opslevel#187]
I'm unable to create a filter like the following:

```HCL
resource "opslevel_filter" "has_repo" {
  name = "has_repo"
  predicate {
    key  = "repository_ids"
    type = "exists"
  }
}
```

My versions are pinned like the following:

```HCL
terraform {
  required_version = "~> 1.5"
  required_providers {
    opslevel = {
      source  = "opslevel/opslevel"
      version = "~> 0.9.0"
    }
  }
}
```

When I check the properties of a similarly hand-made filter via the graphql api, I see the following:

```graphql
{
  "data": {
    "account": {
      "filter": {
        "id": "redacted",
        "name": "test",
        "connective": null,
        "predicates": [
          {
            "caseSensitive": null,
            "keyData": null,
            "value": null,
            "key": "repository_ids",
            "type": "exists"
          }
        ]
      }
    }
  }
}
```

There are two problems.

1) You can see in the above that `connective` is `null`. However when I try to apply without a `connective` set, I get the following error on apply:

```text
Error: Message: Variable $input of type FilterCreateInput! was provided invalid value for connective (Expected "" to be one of: and, or), Locations: [{Line:1 Column:23}], Extensions: map[problems:[map[explanation:Expected "" to be one of: and, or path:[connective]]] value:map[connective: name:has_repo predicates:[map[caseSensitive:true key:repository_ids keyData: type:exists value:]]]]
```

I can workaround this by adding a vestigial `connective = "and"` or `connective = "or"` to the resource's arguments, despite only having one predicate, however this leads me to my second problem.

2) You can see above that `caseSensitive` is `null`. However `case_sensitive` is required for a `predicate` block of the `opslevel_filter` resource type.

When attempting an apply without `case_sensitive` as in the initial sample terraform, I get the following error on plan:

```text
The argument "case_sensitive" is required, but no definition was found.
```
If I add a `case_sensitive = false` or `case_sensitive = true` to the `predicate` block to satisfy the terraform resource schema, I get the following error on apply:

```text
Error: OpsLevel API Errors:
	- 'options' Options property '#/case_sensitive' is outside of the schema
```

**Comment by taimoorgit** [comment]
Thanks a lot of submitting this bug report, it was really easy for me to reproduce the error you're seeing. 

Unfortunately at this time we can offer a partial fix that will unblock you from this `case_insensitive` issue in a limited number of cases while we work on a bigger refactor*.

https://github.com/OpsLevel/terraform-provider-opslevel/pull/188 will allow you to create a filter with a predicate that does not have anything to do with case sensitivity. For example this is now possible without getting the API error:

```
resource "opslevel_filter" "filter_with_predicates" {
  name = "has_repo"
  predicate {
    key  = "repository_ids"
    type = "exists"
  }
}
```

The partial fix will be released in a new version by the end of the next week. Here's a quick rundown on the fix:

1. To enable case sensitivity use `case_sensitive = true`. To disable use `case_insensitive = true` and set `case_sensitive = false`.
2. To create a predicate that has nothing to do with case sensitivity you can just exclude `case_sensitive`.
3. Unfortunately once a predicate has `case_sensitive` attached to it it will not be removed and you have to make a graphql request to fix it. 

---

*We have a refactor coming that will:

1. Upgrade our Terraform SDK to an newer version that doesn't have issues with reading user input
1. Refactor Go Library to deal with nullability in common situations like these.

**Comment by taimoorgit** [comment]
https://github.com/OpsLevel/terraform-provider-opslevel/releases/tag/v0.10.0

Sorry for the very late release, this change has been merged and so you should be able to get around it by upgrading and using `case_sensitive`/`case_insensitive`. 

---

Also, as of right now the Terraform SDK 3 migration for OpsLevel Terraform Provider is being worked on to avoid these kinds of bugs in the future.
