### ISSUE TITLE
opslevel_rubric_category example usage contains "description" which is not a supported attribute

### ISSUE THREAD

**Issue by rene00** [OpsLevel/terraform-provider-opslevel#38]
From https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/resources/rubric_category:
```
resource "opslevel_rubric_category" "example" {
  name = "foo"
  description = "foo category"
}
```

But `description` is not supported. It should be removed from the example.

**Comment by rocktavious** [comment]
Fixed in release v2022.10.22
