### ISSUE TITLE
[bug] 1.1.0 unable to set owner_ids to id reference nor int

### ISSUE THREAD

**Issue by bassco** [OpsLevel/terraform-provider-opslevel#381]
When changing/creating a filter predicate to `owner_ids`, validation fails.

```diff
   predicate {
-    key            = "aliases"
+    key            = "owner_ids"
     type           = "equals"
-    value          = "europe_-_motors"
+    value          = "INT" # "GUID" # an_alias # Causes a Validation bug - state manipulated
     case_sensitive = true
   }
```
The opslevel cli shows that the value is an integer (XXXX - redacted) that relates to the url pattern 
https://app.opslevel.com/teams/XXXX 

The filter shows the INT value, XXXX

```console
opslevel get filter FILTER_GUID
...
    {
      "key": "owner_ids",
      "type": "equals",
      "value": "XXXX",
      "caseSensitive": true
    }
  ]
}
```

When setting the value in the resource to XXXX we get the following validation error.

```console
opslevel_filter.adr-m-0021: Modifying... [id=REDACTED_FILTER_GUID]

Error: opslevel client error

  with opslevel_filter.adr-m-0021,
  on filters.tf line 115, in resource "opslevel_filter" "adr-m-0021":
 115: resource "opslevel_filter" "adr-m-0021" {

Unable to update filter, got error: OpsLevel API Errors:
	- 'value' Invalid global id 'XXXX'

```

When using the FILTER_GUID identifier for the value, the following error occurs.

```console
opslevel_filter.adr-m-0021: Modifying... [id=FILTER_GUID]

Error: Internal Error

  with opslevel_filter.adr-m-0021,
  on filters.tf line 115, in resource "opslevel_filter" "adr-m-0021":
 115: resource "opslevel_filter" "adr-m-0021" {

Could not find matching filter predicate
```

In order to get around this, the statefile is downloaded, the predicate edited to the XXXX value, serial number bumped and the state pushed.

This unblocks our CI pipelines.

**Comment by rocktavious** [comment]
Hey @bassco - After diving into to triage this we've found a bug in our GraphQL api where this is not actually working correctly.  I have attached this issue to our internal issue for the SAAS app and i'll let you know when the GraphQL API is fixed.

The long story short is that the API should not be responding with or expect an INT as the `value` when the `key` is `owner_id` it should always be using the GUID.

**Comment by bassco** [comment]
Ah, brilliant. Thanks for the feedback. We hit this bug in the UI too. The Owner ( Sub Teams ) must be the last filter in the list or else the Edit fails. 

Good to hear it was reproducible. They are easier to fix.

Cheers.

**Comment by davidbloss** [comment]
👋 @bassco we just verified that the internal fix works and also added lots of filter predicate validation. So starting in `v1.2.2` the Terraform provider will help ensure what's provided in `predicate { ... }` blocks will work during `terraform plan` rather than at apply time

**Comment by bassco** [comment]
Validation during `plan` is a significant win! Thanks @davidbloss 
Will update our repo with the new provider when I return from vacation.
