### ISSUE TITLE
Missing documentation of new Aliases list on Team resources

### ISSUE THREAD

**Issue by rocktavious** [OpsLevel/terraform-provider-opslevel#4]
On the `opslevel_team` resource and datasource the API now exposes a Aliases list that captures all of the aliases.  This need to be present in the documentation.

**Comment by davidbloss** [comment]
Closing since [this is covered](https://github.com/OpsLevel/terraform-provider-opslevel/blob/main/examples/resources/opslevel_team/resource.tf#L10)
