### ISSUE TITLE
Custom Property check, cannot specify propertyDefinition

### ISSUE THREAD

**Issue by Anton0** [OpsLevel/terraform-provider-opslevel#414]
I'm trying to create a check for a custom property (hosting_platform) using the `opslevel_check_service_property` resource.

I cannot list the property itself in the `property` attribute, I'm assuming that I should use the `custom_property` value for this attribute.

```
│ Attribute property value must be one of: ["description" "name" "language" "framework" "product" "lifecycle_index" "tier_index" "note" "system" "custom_property"], got: "hosting_platform"
```

However I cannot see a way to specify which custom_property to use in the check, 

```
│ Error: opslevel client error
│ 
│   with opslevel_check_service_property.hosting_platform,
│   on rubric_ownership.tf line 108, in resource "opslevel_check_service_property" "hosting_platform":
│  108: resource "opslevel_check_service_property" "hosting_platform" {
│ 
│ Unable to update check_service_property, got error: OpsLevel API Errors:
│       - 'propertyDefinition' Property definition must be specified for custom properties
```

It's entirely possible I've missed something in the docs / examples but I can't seem to figure out how this is supposed to work!

Terraform Version: Terraform v1.7.0
Provider Version: "1.2.1"

**Comment by rocktavious** [comment]
Hey @Anton0 - You are correct in that this resource is missing the `propertyDefinition` to specify which custom property to target.  Well throw this on our sprint board to get it into the next release.
