### ISSUE TITLE
Missing `opslevel_user` data source

### ISSUE THREAD

**Issue by GilUpstream** [OpsLevel/terraform-provider-opslevel#49]
The provider includes an `opslevel_user` [resource](https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/resources/user) for creating users in OpsLevel, but doesn't provide a similar data source for reading user information from the catalog. This would be helpful for writing terraform configs that depend on users existing in the catalog already. 

Here's an example of a user data source the Datadog terraform provider includes: https://registry.terraform.io/providers/DataDog/datadog/latest/docs/data-sources/user

**Comment by rocktavious** [comment]
Hey @GilUpstream - Thanks for the feature request.

Unfortunately we need to have our GraphQL API updated first to support looking user's up by e-mail instead of ID so that the UX of using this datasource is better.

As the GraphQL API stands today you'd have to do this
```
data "opslevel_user" "kyle" {
  id = "098sd0w98erjklewrlkjsdff098wer098wee908sdf"
}
```

where i would want it to be

```
data "opslevel_user" "kyle" {
  email = "kyle@example.com"
}
```

This request has been put in with our API team but no ETA.

**Comment by GilUpstream** [comment]
@rocktavious Thanks for the quick response! 

> we need to have our GraphQL API updated first to support looking user's up by e-mail
Absolutely! we'd have no use for the data source if we had to use the user id to do the lookup. 

> This request has been put in with our API team but no ETA.
Can we get a `opslevel_users` data source or `members` added to the existing `opslevel_team` data source? or both? Those would work as a workaround for our use case today.

**Comment by rocktavious** [comment]
We could definitely do `opslevel_users`.  I'll see if we can enqueue this next week and get it in before the holidays start.

We still have some outstanding questions to answer about teams and groups internally before we bake it into terraform.  Would just `opslevel_users` suffice?

**Comment by GilUpstream** [comment]
> Would just `opslevel_users` suffice?

@rocktavious That would be super helpful. Thanks!

**Comment by GilUpstream** [comment]
@rocktavious 👋🏼 any update on the `opslevel_users` data source?

**Comment by rocktavious** [comment]
Sorry @GilUpstream for the radio silence.  Long story short we were not able to get to this before the holidays and I just got back from PTO this week.  I'll make sure this makes it into our next release which is TBD yet.
