### ISSUE TITLE
Changelog file doesn't actually show versions

### ISSUE THREAD

**Issue by ricoli-motorway** [OpsLevel/terraform-provider-opslevel#532]
Could the versions please be added to the Changelog file so that we can tell what was changed in each version? https://github.com/OpsLevel/terraform-provider-opslevel/blob/main/CHANGELOG.md

**Comment by rocktavious** [comment]
Hey @ricoli-motorway - thats definitely not suppose to be like that.  We'll look into fixing that.  THanks for letting us know!

**Comment by ricoli-motorway** [comment]
hi @davidbloss - it seems that the PR didn't quite fix it, as there's still no version showing up, only a date? There's a link now, which is a good step forward, but would be great to not have to click to know which version it is about... https://github.com/OpsLevel/terraform-provider-opslevel/blob/main/CHANGELOG.md
