### ISSUE TITLE
Plans fail when a repo is archived in GitHub

### ISSUE THREAD

**Issue by GilUpstream** [OpsLevel/terraform-provider-opslevel#56]
### Error Message
```
│ Error: unable to find service repository with id 'xxxxxxxxx' on service 'abc'
│
│   with opslevel_service_repository.github["abc"],
│   on main.tf line 31, in resource "opslevel_service_repository" "github":
│   31: resource "opslevel_service_repository" "github" {
```

###  Terraform Version

```
terraform -version
Terraform v1.3.7
```
### Expected Behavior

terraform plan succeeds

### Actual Behavior

terraform plan fails

### Steps to Reproduce

1.  connect GitHub to OpsLevel
2.  write terraform configs with an `opslevel_service` and `opslevel_service_repository` tying a GitHub repo to an OpsLevel service.
3.  terraform apply
4.  archive the repo from above in GitHub
5. terraform plan (`fails`)

### References

-   [https://discuss.hashicorp.com/t/reconcile-destroyed-resources/14207/2](https://discuss.hashicorp.com/t/reconcile-destroyed-resources/14207/2)

**Comment by rocktavious** [comment]
Thanks @GilUpstream - We are going to take this internally for a bit and discuss options/solutions.  While on its face it seems like a quick fix we want to make sure we are doing the right thing here - both from Terraform documentation for provider developers and just in general customer UX.
