### ISSUE TITLE
Missing `opslevel_service_dependency` resource

### ISSUE THREAD

**Issue by GilUpstream** [OpsLevel/terraform-provider-opslevel#62]
We'd like to manage our service dependencies in terraform, but the provider is currently missing an `opslevel_service_dependency` resource. Looks like there is an API endpoint for the provider to interact with; can we get it added to the provider?

**Comment by rocktavious** [comment]
Hey @GilUpstream - Service Dependencies has yet to be implemented in opslevel-go.  It is currently on our backlog but no ETA yet.

I'll keep this issue alive until we get that rolled out but sorry there is not ETA for this yet.

**Comment by rocktavious** [comment]
@GilUpstream - https://github.com/OpsLevel/terraform-provider-opslevel/pull/79 will be coming in the next release
