### ISSUE TITLE
opslevel_services all fails with timeout set

### ISSUE THREAD

**Issue by davidferdinand** [OpsLevel/terraform-provider-opslevel#77]
having upgraded to version 0.8.1 and setting timeout the data resource "opslevel_services" "all" with not filters set fails with the below error:

`Variable $first is used by ServiceTagsList but not declared, Locations: [{Line:1 Column:108}], Extensions: map[code:variableNotDefined variableName:first]`

without the timeout set the call timesout anyway.

**Comment by davidferdinand** [comment]
updated to 0.8.2 and not having this issue...

**Comment by rocktavious** [comment]
Thanks for the update and closing the issue @davidferdinand (sorry we are not more responsive in here - our customer success process is not really plugged into Github issues so its a "best effort" that I try to do over here)
