### ISSUE TITLE
Missing `opslevel_repository` resource

### ISSUE THREAD

**Issue by GilUpstream** [OpsLevel/terraform-provider-opslevel#83]
We'd like to manage repo ownership in terraform, but the provider is currently missing an `opslevel_repository` resource. Looks like there is an API endpoint for the provider to interact with; can we get it added to the provider?

**Comment by rocktavious** [comment]
@GilUpstream - This will be in the next release - May 19th

**Comment by GilUpstream** [comment]
@rocktavious this will be huge for us! thanks!
